# This is a basic workflow to help you get started with Actions

name: Build & Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ release ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.91.2

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install hugo executable binary
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb -O /tmp/hugo.deb
          sudo dpkg -i /tmp/hugo.deb
          hugo version

      - name: Prepare the git worktree
        run: |
          rm -rf $GITHUB_WORKSPACE/public

          git fetch origin
          git worktree add -B gh-pages public origin/gh-pages

      - name: Build through hugo
        run: hugo

      - name: Push to gh-pages branch
        run: |
          cd $GITHUB_WORKSPACE/public
          cp index.xml feed.xml

          git add --all

          git config user.name github-actions
          git config user.email github-actions@github.com

          git commit -m 'publish from github actions'
          git push origin gh-pages

